return {
	metadataFieldsForPhotos = {
		{
			id = "aiLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiLastRun=Last AI run"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiModel=AI model"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditLastRun=Last AI edit run"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditModel=AI edit model"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditStatus",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditStatus=AI edit status"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditSummary",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditSummary=AI edit summary"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditWarnings",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditWarnings=AI edit warnings"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditRecipe",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditRecipeJson=AI edit recipe JSON"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "photoContext",
			title = LOC("$$$/StyleAI/AIMetadataProvider/photoContext=Photo context"),
			dataType = "string",
			readOnly = false,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullDecision",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullDecision=Culling decision"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullGroupId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullGroupId=Culling group ID"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullGroupType",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullGroupType=Culling group type"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullGroupRank",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullGroupRank=Culling rank"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullGroupWinner",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullGroupWinner=Group winner"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullScore",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullScore=Culling score"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullReasonCodes",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullReasonCodes=Culling reason codes"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullExplanation",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullExplanation=Culling explanation"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullSharpness",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullSharpness=Sharpness"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullExposure",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullExposure=Exposure"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullNoise",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullNoise=Noise penalty"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullTechnicalScore",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullTechnicalScore=Technical score"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullAesthetic",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullAesthetic=Aesthetic score"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullFaceCount",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullFaceCount=Face count"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullFaceSharpness",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullFaceSharpness=Face sharpness"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullFaceProminence",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullFaceProminence=Face prominence"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullFaceVisibility",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullFaceVisibility=Face visibility"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullFaceScore",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullFaceScore=Face score"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullOcclusion",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullOcclusion=Occlusion penalty"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullEyeOpenness",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullEyeOpenness=Eye openness"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "cullBlinkPenalty",
			title = LOC("$$$/StyleAI/AIMetadataProvider/cullBlinkPenalty=Blink penalty"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "keywords",
			title = LOC("$$$/StyleAI/AIMetadataProvider/keywords=AI Keywords"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "globalPhotoId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoId=Global Photo ID"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = false,
			version = 2,
		},
		{
			id = "globalPhotoIdFileSize",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdFileSize=Global Photo ID File Size"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdFileModificationDate",
			title = LOC(
				"$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdModificationDate=Global Photo ID File Modification Date"
			),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdAlgorithm",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdAlgorithm=Global Photo ID Algorithm"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
	},

	schemaVersion = 31,
	updateFromEarlierSchemaVersion = function(catalog, previousSchemaVersion, progressScope)
		catalog:assertHasPrivateWriteAccess("AIMetadataProvider.updateFromEarlierSchemaVersion")
	end,
}
