return {
	metadataFieldsForPhotos = {
		{
			id = "aiLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiLastRun=StyleAI Metadata Date"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiModel=StyleAI Metadata Model"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditLastRun=StyleAI Edit Date"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditModel=StyleAI Edit Model"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "aiEditStatus",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditStatus=Legacy StyleAI edit status"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "aiEditApplied",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditApplied=StyleAI Edit Applied"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditState",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditState=StyleAI Edit State"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditReview",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditReview=StyleAI Edit Review"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditInferenceId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditInferenceId=AI edit inference ID"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "aiEditSummary",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditSummary=StyleAI Edit Summary"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditWarnings",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditWarnings=StyleAI Edit Warnings"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditRecipe",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditRecipeJson=AI edit recipe JSON"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			-- Durable Lightroom-side outbox used between Develop application and
			-- the backend receipt. It must be declared even though it is never shown.
			id = "pendingAiEditApplicationEvent",
			title = LOC("$$$/StyleAI/AIMetadataProvider/PendingAiEditApplicationEvent=Pending AI edit application event"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "photoContext",
			title = LOC("$$$/StyleAI/AIMetadataProvider/photoContext=StyleAI Photo Instructions"),
			dataType = "string",
			readOnly = false,
			searchable = true,
			browsable = true,
		},

		{
			id = "keywords",
			title = LOC("$$$/StyleAI/AIMetadataProvider/keywords=Legacy StyleAI Keywords"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoId=Global Photo ID"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
			version = 2,
		},
		{
			id = "globalPhotoIdFileSize",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdFileSize=Global Photo ID File Size"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdFileModificationDate",
			title = LOC(
				"$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdModificationDate=Global Photo ID File Modification Date"
			),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdAlgorithm",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdAlgorithm=Global Photo ID Algorithm"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
	},

	schemaVersion = 34,
	updateFromEarlierSchemaVersion = function(catalog, previousSchemaVersion, progressScope)
		catalog:assertHasPrivateWriteAccess("AIMetadataProvider.updateFromEarlierSchemaVersion")
	end,
}
