return {
	metadataFieldsForPhotos = {
		{
			id = "aiLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiLastRun=Last AI run"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/aiModel=AI model"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditLastRun",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditLastRun=Last AI edit run"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditModel",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditModel=AI edit model"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditStatus",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditStatus=AI edit status"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditInferenceId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditInferenceId=AI edit inference ID"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = false,
		},
		{
			id = "aiEditSummary",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditSummary=AI edit summary"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditWarnings",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditWarnings=AI edit warnings"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "aiEditRecipe",
			title = LOC("$$$/StyleAI/AIMetadataProvider/AiEditRecipeJson=AI edit recipe JSON"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "photoContext",
			title = LOC("$$$/StyleAI/AIMetadataProvider/photoContext=Photo context"),
			dataType = "string",
			readOnly = false,
			searchable = true,
			browsable = true,
		},

		{
			id = "keywords",
			title = LOC("$$$/StyleAI/AIMetadataProvider/keywords=AI Keywords"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = true,
		},
		{
			id = "globalPhotoId",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoId=Global Photo ID"),
			dataType = "string",
			readOnly = true,
			searchable = true,
			browsable = false,
			version = 2,
		},
		{
			id = "globalPhotoIdFileSize",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdFileSize=Global Photo ID File Size"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdFileModificationDate",
			title = LOC(
				"$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdModificationDate=Global Photo ID File Modification Date"
			),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
		{
			id = "globalPhotoIdAlgorithm",
			title = LOC("$$$/StyleAI/AIMetadataProvider/GlobalPhotoIdAlgorithm=Global Photo ID Algorithm"),
			dataType = "string",
			readOnly = true,
			searchable = false,
			browsable = false,
		},
	},

	schemaVersion = 32,
	updateFromEarlierSchemaVersion = function(catalog, previousSchemaVersion, progressScope)
		catalog:assertHasPrivateWriteAccess("AIMetadataProvider.updateFromEarlierSchemaVersion")
	end,
}
