return {
	title = "StyleAI",
	id = "styleaiTagset",
	items = {
		"com.adobe.filename",
		"com.adobe.copyname",
		"com.adobe.folder",
		"com.adobe.dateTimeOriginal",
		"com.adobe.rating",
		"com.adobe.colorLabels",
		"com.adobe.GPS",
		"com.adobe.exposure",
		"com.adobe.exposureProgram",
		"com.adobe.exposureBiasValue",
		"com.adobe.focalLength",
		"com.adobe.isoSpeed",
		"com.adobe.lensModel",
		"com.adobe.model",
		"com.adobe.separator",
		"com.adobe.title",
		{ "com.adobe.caption", height_in_lines = 5 },
		{ "com.adobe.altTextAccessibility", height_in_lines = 5 },
		"com.adobe.separator",
		_PLUGIN.id .. ".aiModel",
		_PLUGIN.id .. ".aiLastRun",
		_PLUGIN.id .. ".aiEditApplied",
		_PLUGIN.id .. ".aiEditState",
		_PLUGIN.id .. ".aiEditReview",
		_PLUGIN.id .. ".aiEditLastRun",
		{ _PLUGIN.id .. ".aiEditSummary", height_in_lines = 4 },
		{ _PLUGIN.id .. ".aiEditWarnings", height_in_lines = 4 },

		{ _PLUGIN.id .. ".photoContext", height_in_lines = 5 },
	},
}
