import io
import zipfile
from typing import Any, Dict, List
import uuid


def generate_xmp_preset(name: str, group: str, settings: Dict[str, Any]) -> str:
    """Generate a Lightroom Classic .xmp preset from a dictionary of develop settings."""

    # Base XMP template
    lines = [
        '<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.0-c000 1.000000, 0000/00/00-00:00:00        ">',
        ' <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
        '  <rdf:Description rdf:about=""',
        '    xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"',
        '   crs:PresetType="Normal"',
        '   crs:Cluster=""',
        f'   crs:UUID="{str(uuid.uuid4()).upper()}"',
        '   crs:SupportsAmount="False"',
        '   crs:SupportsColor="True"',
        '   crs:SupportsMonochrome="True"',
        '   crs:SupportsHighDynamicRange="True"',
        '   crs:SupportsNormalDynamicRange="True"',
        '   crs:SupportsSceneReferred="True"',
        '   crs:SupportsOutputReferred="True"',
        '   crs:RequiresRgbMatrix="False"',
        '   crs:CameraModelRestriction=""',
        '   crs:Copyright=""',
        '   crs:ContactInfo=""',
        '   crs:Version="14.4"',
        '   crs:ProcessVersion="11.0"',
    ]

    # Add settings
    for key, value in settings.items():
        if isinstance(value, bool):
            val_str = "True" if value else "False"
        elif isinstance(value, (int, float)):
            val_str = str(value)
        elif isinstance(value, str):
            val_str = value
        else:
            continue  # Skip complex nested objects like Look or point curves for now

        lines.append(f'   crs:{key}="{val_str}"')

    lines.append('   crs:HasSettings="True">')

    # Add metadata
    lines.extend(
        [
            "   <crs:Name>",
            "    <rdf:Alt>",
            f'     <rdf:li xml:lang="x-default">{name}</rdf:li>',
            "    </rdf:Alt>",
            "   </crs:Name>",
            "   <crs:ShortName>",
            "    <rdf:Alt>",
            '     <rdf:li xml:lang="x-default"/>',
            "    </rdf:Alt>",
            "   </crs:ShortName>",
            "   <crs:SortName>",
            "    <rdf:Alt>",
            '     <rdf:li xml:lang="x-default"/>',
            "    </rdf:Alt>",
            "   </crs:SortName>",
            "   <crs:Group>",
            "    <rdf:Alt>",
            f'     <rdf:li xml:lang="x-default">{group}</rdf:li>',
            "    </rdf:Alt>",
            "   </crs:Group>",
            "   <crs:Description>",
            "    <rdf:Alt>",
            '     <rdf:li xml:lang="x-default">Generated by StyleAI</rdf:li>',
            "    </rdf:Alt>",
            "   </crs:Description>",
            "  </rdf:Description>",
            " </rdf:RDF>",
            "</x:xmpmeta>",
        ]
    )

    return "\n".join(lines)


def create_presets_zip(styles: List[Dict[str, Any]], recipe_fetcher) -> bytes:
    """Create a ZIP archive of .xmp preset files grouped by camera model."""
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for style in styles:
            style_id = style.get("style_id")
            if not style_id:
                continue

            recipe = recipe_fetcher(style_id)
            if not recipe:
                continue

            # Formatting the name and group
            camera_model = style.get("camera_model", "Unknown Camera")
            style_name = (
                style.get("style_name") or style.get("user_style_name") or style_id
            )

            # Safe filename characters
            safe_name = "".join(
                c for c in style_name if c.isalnum() or c in (" ", "-", "_", "[", "]")
            ).strip()
            if not safe_name:
                safe_name = style_id

            group_name = f"{camera_model} Signature Styles"

            xmp_content = generate_xmp_preset(
                name=style_name, group=group_name, settings=recipe
            )

            # Path inside ZIP: e.g., "Nikon Z5 Signature Styles/NIKON Z 5 — Landscape.xmp"
            zip_path = f"{group_name}/{safe_name}.xmp"

            zip_file.writestr(zip_path, xmp_content.encode("utf-8"))

    return zip_buffer.getvalue()
